### ISSUE TITLE
Extractor Silo Connector Requires Update

### ISSUE THREAD

**Issue by laanp** [djmonkeyuk/nms-base-builder#48]
One side of the extractor silo is unmatched to the remaining connectors (from previous  versions) and will not receive snap connection for piplines.
![Silo Connector](https://user-images.githubusercontent.com/72280606/94969048-e1930600-04b6-11eb-84cc-8464e2102817.jpg)

**Comment by djmonkeyuk** [comment]
try this:

https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.2
