### ISSUE TITLE
Multiple connection points created when connect button is utilized

### ISSUE THREAD

**Issue by laanp** [djmonkeyuk/nms-base-builder#67]
When connecting 2 objects that have electrical connection points, the active object will receive 3 x connection points when clicking on the "connect" button.  This may be an unintended effect of the updated "connect many" feature.

![Clipboard02](https://user-images.githubusercontent.com/72280606/111932887-a17f0a00-8a7b-11eb-863d-6bfa3ddbc23f.jpg)

**Comment by davebastian** [comment]
I can confirm this issue. I've taken to manually deleting the extraneous connection points, but, depending on what you're wiring, this quickly becomes onerous.

I think the extra points clear if you export/reimport your build, but even that workaround is cumbersome.

**Comment by djmonkeyuk** [comment]
Try this : https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.1
