### ISSUE TITLE
Frontier - Asset Browser v 2.0.0

### ISSUE THREAD

**Issue by Mike-Blackwell** [djmonkeyuk/nms-base-builder#71]
Charlie,

I happen upon a webpage which seem to have numerous NMS Construction parts with associated graphics, I did not do a one for one comparison but found a few discrepancies as denoted below:

1) two lighting fixture names that need to be swapped Splayed Hanging Lamp and Circles Hanging Light
2) Light Box (small) should be Light Box
3) Change OUNDATIO to Foundation
4) Change Lockbox to Open Tall Moulded Box
5) Missing Pioneers Expedition Statue
6) Missing Bubble Duct, L-Shaped, T-Shaped and X-Shaped
7) Missing Hazard Decal, Warning Decal, Horrific Decal, Tentacled Decal
8) Floral Canister should be under Derelict Freighter Salvage
9) Detoxified Slime should be under Decorative Plants
10) Missing Saucer Fungus, Cave Creeper, Troglotulip, Veined Flat Caps, Fingery Deposit which all should be under Decorative Plants
11) Missing RGB Fireworks, Atlas Fireworks, Atlas Firework (Blue), Atlas Firework (Red), Atlas Firework (Yellow)

**Comment by davebastian** [comment]
1. FWIW, bubble duct part IDs (fairly self-explanatory) are as follows:
BASE_BUBPIPE
BASE_BUBPIPE_L
BASE_BUBPIPE_T
BASE_BUBPIPE_X

2. Expedition 4: Emergence (October) introduced the Titanic Trophy.

3. Under Furnishings, there's a misspelled word; there's no 'a' in 'opulent.' The item should be "Opulent Tapestry."

**Comment by djmonkeyuk** [comment]
I think most of this should be sorted now in later versions. Closing issue. Feel free to make another one if you notice anything.
