### ISSUE TITLE
V.2.0.4 Asset Browser missing many preview thumbnails

### ISSUE THREAD

**Issue by davebastian** [djmonkeyuk/nms-base-builder#78]
By my count, about 90 parts in the Asset Browser are missing preview thumbnails (also, some are displaying their object names rather than their in-game part names). Attached are some screenshots of representative tabs (note: I edited 2 of the attached JPEGs with red Xs to make some of the missing thumbnails easier to spot).

![asset-browser-01](https://user-images.githubusercontent.com/20446496/218814724-e396c716-63b6-4442-a6cf-e1f39d4b0a4a.jpg)
![asset-browser-02](https://user-images.githubusercontent.com/20446496/218814750-8a3815e8-bd66-4e0a-9120-58b471db7df0.jpg)
![asset-browser-03](https://user-images.githubusercontent.com/20446496/218814773-f4ede5b1-5642-4717-8c0a-1fc0d89992ad.jpg)

**Comment by Voldrang** [comment]
FWIW, I have may have a source for high-quality PNGs of many of the missing parts, if that's helpful. (I just don't know how to get them into the Asset Browser or else I'd fix it for myself.)

**Comment by djmonkeyuk** [comment]
Should be sorted in latest versions.
