### ISSUE TITLE
Snap Points Incorrect for Large Structures (issue persists in 2.1.0)

### ISSUE THREAD

**Issue by davebastian** [djmonkeyuk/nms-base-builder#79]
Attaching a **door** or **corridor** to a large structure (Cuboid Room, Square Room, Cylindrical Room, Bio-Dome, Deepwater Chamber) using NMS Base Builder fails to make an entrance to the structure (see attached JPEGs for reference).

![No-Man's-Sky-Screenshot-2023 02 13---21 55 19](https://user-images.githubusercontent.com/20446496/218818836-59de6be0-3171-4b92-aa7e-e854da103371.jpg)
![No-Man's-Sky-Screenshot-2023 02 13---21 54 43 41](https://user-images.githubusercontent.com/20446496/218818852-3b81befc-6446-4cb3-916f-6ceb7e44db57.jpg)
![No-Man's-Sky-Screenshot-2023 02 13---21 49 08](https://user-images.githubusercontent.com/20446496/218818873-4f58f5cd-de9d-4535-b044-f3015d346492.jpg)
![No-Man's-Sky-Screenshot-2023 02 13---21 50 03](https://user-images.githubusercontent.com/20446496/218818907-3e18fb24-7692-4cd6-96b4-420704d446c0.jpg)
![No-Man's-Sky-Screenshot-2023 02 13---21 50 28](https://user-images.githubusercontent.com/20446496/218818919-2415b8d5-1e03-409a-88ea-5f3b8ac64cbc.jpg)
![No-Man's-Sky-Screenshot-2023 02 14---08 38 36](https://user-images.githubusercontent.com/20446496/218818927-33091732-442c-4b9c-a938-552e36c1d37e.jpg)
![No-Man's-Sky-Screenshot-2023 02 14---08 41 06](https://user-images.githubusercontent.com/20446496/218818937-e650365d-da4a-456e-b446-4e4ac7030ca5.jpg)
![No-Man's-Sky-Screenshot-2023 02 14---08 39 58](https://use
![No-Man's-Sky-Screenshot-2023 02 14---08 42 32](https://user-images.githubusercontent.com/20446496/218818962-99b0b53a-d95a-42b2-b085-cbe82941bfb1.jpg)
![No-Man's-Sky-Screenshot-2023 02 14---08 41 56](https://user-images.githubusercontent.com/20446496/218818952-60423d44-ca1f-47c2-8f7c-98cb030b1d2f.jpg)
r-images.githubusercontent.com/20446496/218818946-dd6a9095-fd4b-4cbf-a601-316aa852db8b.jpg)
![No-Man's-Sky-Screenshot-2023 02 14---08 39 58](https://user-images.githubusercontent.com/20446496/218819177-6bd1d6bc-2757-4f92-a28a-fcbae88fab93.jpg)

**Comment by Voldrang** [comment]
Issue persists in 2.0.5, and affects prefabs (including corridors).

**Comment by Voldrang** [comment]
Issue persists in 2.0.7.

FWIW, per Peter Laan (3/30/2022):

"This might have been partly my fault, since I asked Charlie to move them when Frontiers first came out…several updates later, they fixed them, and the snap points are now off…🤪"

**Comment by Voldrang** [comment]
This issue persists in 2.1.0

**Comment by djmonkeyuk** [comment]
Try this: https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.1
