### ISSUE TITLE
Proxy object model(s) for Gek statue are same as Blob statue

### ISSUE THREAD

**Issue by davebastian** [djmonkeyuk/nms-base-builder#80]
Place a Gek statue, and what you get for a proxy is the Blob statue. Seems like a minor quibble, I know, when there's so much else right with NMS Base Builder, but I was recently working on a base that used both statues, and it quickly became very confusing as to which was which.
![gek-blob](https://user-images.githubusercontent.com/20446496/225956831-9f3a0a2e-1d9a-4d85-bc46-1e6ca3daf028.jpg)
"Will the real Blob please step forward?"

Incidentally, is there any rhyme or reason as to why some of the models are fairly detailed (good representation in Blender), while others lack much detail (organic frigate calf comes to mind), and involve guesswork that's only cleared up in the game?

**Comment by djmonkeyuk** [comment]
https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.2
