### ISSUE TITLE
Error in python clicking to open asset browser and preset folder buttons

### ISSUE THREAD

**Issue by johnnyl33** [djmonkeyuk/nms-base-builder#82]
Hello, first of all, I wanna thank you all very much for this amazing Blender addon; the issue I'm having is not being able to access the "Launch Asset Browser", when I click the button, this message appears:
```
Python: Traceback (most recent call last):
  File "/home/asdasd/.config/blender/3.5/scripts/addons/no_mans_sky_base_builder/__init__.py", line 1246, in execute
    subprocess.Popen("python \"{}\"".format(loader))
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python "/home/asdasd/.config/blender/3.5/scripts/addons/no_mans_sky_base_builder/asset_browser/load.py"'
```
 
and this message shows when I click on the "open preset folder" button:
```
Python: Traceback (most recent call last):
  File "/home/asdasd/.config/blender/3.5/scripts/addons/no_mans_sky_base_builder/__init__.py", line 1266, in execute
    os.startfile(PRESET_PATH)
AttributeError: module 'os' has no attribute 'startfile'
```
![Screenshot_20230511_233741](https://github.com/djmonkeyuk/nms-base-builder/assets/1273199/24f1b51d-e839-4466-9f83-11617dd34c5c)
![Screenshot_20230509_124145](https://github.com/djmonkeyuk/nms-base-builder/assets/1273199/3216dcd4-1c76-4212-b6fc-97d7cad1123a)

I did installed the "bpy_externall" addon before this one, my 3.5 blender installation runs on Manjaro Linux with Python 3.10.10.

Thanks in advance, for any help with this.

**Comment by dsalt** [comment]
See #97.
