### ISSUE TITLE
Base Teleport Module/TELEPORTER lacks electrical connection snap point (v2.0.7 current)

### ISSUE THREAD

**Issue by Voldrang** [djmonkeyuk/nms-base-builder#88]
POWER_CONTROL point will not connect to the Base Teleport Module and instead returns error message: "Make sure you have two or more electrical points selected."

**Comment by djmonkeyuk** [comment]
Try this: https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.1
