### ISSUE TITLE
AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found

### ISSUE THREAD

**Issue by EvilSupahFly** [djmonkeyuk/nms-base-builder#89]
I'm trying to run the NMS Base Builder in Blender on both Windows and Linux, but it crashes when processing the JSON for my base with the same error on both:

`AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found`

Here are some relevant links:
Base JSON: https://pastebin.com/k9W79cFf
Blender Error (Windows): https://pastebin.com/P76ULbFT
Blender Error (Linux): https://pastebin.com/PEbTzq1p

Other "Good To Know" things:
Python on Windows version: Python 3.12.2
Python on Linux version: Python 3.10.12
Blender on Windows version: Blender 4.0.2
Blender on Linux version: Blender 4.0.2-flatpak

Initially, I thought the issue was because I was running this natively on Linux, so I installed Python and Blender to the same WINE prefix I have NMS installed to, but that failed too. After some digging I stumbled upon [this StackOverflow post](https://stackoverflow.com/questions/77807142/attributeerror-calling-operator-bpy-ops-import-scene-obj-error-could-not-be) which says `bpy.ops.import_scene.obj` was changed to `bpy.ops.wm.obj_import(filepath='')` in v4 of blender's api for python, along with the suggestion to downgrade BPY using `pip install bpy==3.6.0` which was initially successful, however, since Blender is installed via FlatPak on Linux (a completely self-contained, sandboxed framework), this didn't actually fix the error since the framework itself wasn't modified - just my local user cache:

```
evilsupahfly on Black-Beast at Wed 20 Mar 2024 17:19:38 EDT
[~] pip install bpy==3.6.0
Defaulting to user installation because normal site-packages is not writeable
Collecting bpy==3.6.0
  Downloading bpy-3.6.0-cp310-cp310-manylinux_2_28_x86_64.whl (371.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.4/371.4 MB 1.4 MB/s eta 0:00:00
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from bpy==3.6.0) (1.24.2)
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (from bpy==3.6.0) (0.29.28)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bpy==3.6.0) (2.31.0)
Collecting zstandard
  Downloading zstandard-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->bpy==3.6.0) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->bpy==3.6.0) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->bpy==3.6.0) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bpy==3.6.0) (3.1.0)
Installing collected packages: zstandard, bpy
Successfully installed bpy-3.6.0 zstandard-0.22.0
```

So I tried to do the same thing on Windows, but that was even worse because the package is only compatible with Python 3.7:

```
C:\>pip3 install bpy==3.6.0
ERROR: Ignored the following versions that require a different python version: 2.82.1 Requires-Python >=3.7, <3.8
ERROR: Could not find a version that satisfies the requirement bpy==3.6.0 (from versions: none)
ERROR: No matching distribution found for bpy==3.6.0
```

I'm hesitant to go mucking about in the source because I'm about as skilled at writing Python as Brad Pitt is at speaking Mandarin, or I'd simply go in and fix it myself.

Side note: I tried the stand-alone version on Nexus Mods, and while it does render the base using the JSON given without issue, under WINE, panning and object manipulation move the entire application window instead of the object map contained within the window. That, however, is probably more of a WINE issue, rather than something that can be addressed here.

**Comment by djmonkeyuk** [comment]
Downgrade Blender to a 3.x version and it should work. With 4.x they
removed a fundamental function call that this uses, I still need to work on
fixing that.

**Comment by EvilSupahFly** [comment]
> Downgrade Blender to a 3.x version and it should work. With 4.x they removed a fundamental function call that this uses, I still need to work on fixing that.

Blender's FlatPak install is only v4, but I did find 3.6.10 under "LTS" on their site, so I installed it, and that works quite nicely. Thanks!

![Screenshot from 2024-03-21 10-41-54](https://github.com/djmonkeyuk/nms-base-builder/assets/3280846/4eb2ce65-8ecf-47a8-befa-0c470c49a102)
