### ISSUE TITLE
2.1.0 Robotic Hand / Construct Digits issue

### ISSUE THREAD

**Issue by Voldrang** [djmonkeyuk/nms-base-builder#92]
Construct Digits (BLD_BUI_HAND): snap point incorrectly placed, hand oriented opposite to placement in game; in other words, hand placed facing palm-up in game results in palm-down orientation in Blender, and vice versa.

**Comment by djmonkeyuk** [comment]
Try this: https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.1
