### ISSUE TITLE
2.1.1 - Issue with Holographic Friend (BLD_HOLOGEK)

### ISSUE THREAD

**Issue by Voldrang** [djmonkeyuk/nms-base-builder#94]
BLD_HOLOGEK model represented by miniaturized cube in Blender.

**Comment by Voldrang** [comment]
I've found the attached model to be a helpful substitute.
[FRE_FACE_WINDOW.zip](https://github.com/djmonkeyuk/nms-base-builder/files/14899622/FRE_FACE_WINDOW.zip)

**Comment by djmonkeyuk** [comment]
https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.2
