### ISSUE TITLE
2.1.1 - Freighter Reinforced Window (FRE_FACE_WINDOW) lacks model

### ISSUE THREAD

**Issue by Voldrang** [djmonkeyuk/nms-base-builder#96]
Long-standing issue: Freighter Reinforced Window (FRE_FACE_WINDOW) lacks model--it only displays as a snap point.

**Comment by Voldrang** [comment]
I've found the attached model to be a helpful subs
[FRE_FACE_WINDOW.zip](https://github.com/djmonkeyuk/nms-base-builder/files/14899637/FRE_FACE_WINDOW.zip)
titute.

**Comment by djmonkeyuk** [comment]
https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.2
