### ISSUE TITLE
Docs don't mention dependency on PySide6

### ISSUE THREAD

**Issue by dsalt** [djmonkeyuk/nms-base-builder#98]
```
Traceback (most recent call last):
  File "/home/user/.config/blender/3.4/scripts/addons/no_mans_sky_base_builder/asset_browser/load.py", line 41, in <module>
    import asset_browser.main
  File "/home/user/.config/blender/3.4/scripts/addons/no_mans_sky_base_builder/asset_browser/../asset_browser/main.py", line 10, in <module>
    from PySide6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PySide6'
```

I *think* that `python3-pyside6.qtcore`, `python3-pyside6.qtgui` & `python3-pyside6.qtwidgets` are required (Devuan, therefore also Debian; likely similar on Ubuntu etc.).

I note that these packages are presently in unstable only (not even in testing yet!), which means that as I'm running Devuan stable, I'm going to have to build the packages locally if I don't want to pull in a *lot* of packages from there.

**Comment by djmonkeyuk** [comment]
PySide is required for the Asset Browser. I will add it to the docs!

You might want to try PySide2 if you're eager to get it working on Linux, assuming that that is a stable release...

**Comment by dsalt** [comment]
Seems to be working with that (and the corresponding code changes, now present in my pull request).

Installing `python3-pyside6.qtwidgets` or `python3-pyside2.qtwidgets` should be sufficient on Debian, Devuan, Ubuntu and similar distributions. Devuan's `python3-pyside2.qtwidgets`, which I've now installed and which is identical to Debian's, depends on the the other two.
